baseURL = "https://victorious-desert-01d544110.2.azurestaticapps.net/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "Junjie's Blog"
theme = "PaperMod"
paginate = 10

[params]
  env = "production"
  description = "Notes on career, tech, and life"
  author = "Junjie Li"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  defaultTheme = "auto"
  disableThemeToggle = false

  [params.homeInfoParams]
    Title = "Hey there 👋"
    Content = "Notes on career, tech, and life."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/MuyangAmigo"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
